---
Attribute:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Relation
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude: []
DataClump:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Function
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude: []
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Function::Predicate#new_from_enumerable_predicate
  - Axiom::SQL::Generator::Function::Predicate#optional?
  - Axiom::SQL::Generator::Function::Predicate#visit_axiom_function_predicate_inequality
  - Axiom::SQL::Generator::Identifier#visit_identifier
  - Axiom::SQL::Generator::Identifier#visit_identifier
  - Axiom::SQL::Generator::Literal#visit_numeric
  - Axiom::SQL::Generator::Literal#visit_string
  - Axiom::SQL::Generator::Literal#visit_string
  - Axiom::SQL::Generator::Relation#column_list_for
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Function::Predicate#new_from_enumerable_predicate
  max_params: 2
  overrides:
    initialize:
      max_params: 3
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Relation::Materialized#visit_axiom_relation_materialized
  - Axiom::SQL::Generator::Visitor#self.handlers
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Function::Predicate#inequality_sql
  - Axiom::SQL::Generator::Function::Predicate#visit_axiom_function_predicate_equality
RepeatedConditional:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Relation
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Relation::Binary
  - Axiom::SQL::Generator::Relation::Unary
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Relation
  - Axiom::SQL::Generator::Relation::Unary
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
  - Date#iso8601
  - DateTime#iso8601_timediv
  - Axiom::SQL::Generator::Function::Predicate#exclusive_range_exclusion_sql
  - Axiom::SQL::Generator::Function::Predicate#exclusive_range_inclusion_sql
  - Axiom::SQL::Generator::Function::Predicate#inequality_expressions
  - Axiom::SQL::Generator::Function::Predicate#visit_axiom_function_predicate_inequality
  - Axiom::SQL::Generator::Literal#visit_class
  - Axiom::SQL::Generator::Relation#column_list_for
  - Axiom::SQL::Generator::Relation#columns_for
  - Axiom::SQL::Generator::Relation#implicit_columns
  - Axiom::SQL::Generator::Relation#self.visit
  - Axiom::SQL::Generator::Relation::Binary#set_operands
  - Axiom::SQL::Generator::Relation::Binary#visit_axiom_algebra_join
  - Axiom::SQL::Generator::Relation::Binary#visit_axiom_algebra_product
  - Axiom::SQL::Generator::Relation::Insertion#visit_axiom_relation_operation_insertion
  - Axiom::SQL::Generator::Relation::Materialized#generate_sql
  - Axiom::SQL::Generator::Relation::Set#self.normalize_operand_headers
  - Axiom::SQL::Generator::Relation::Set#visit_axiom_algebra_difference
  - Axiom::SQL::Generator::Relation::Set#visit_axiom_algebra_intersection
  - Axiom::SQL::Generator::Relation::Set#visit_axiom_algebra_union
  - Axiom::SQL::Generator::Relation::Unary#reset_query_state
  - Axiom::SQL::Generator::Relation::Unary#subquery_for
  - Axiom::SQL::Generator::Relation::Unary#summarize_per
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_algebra_extension
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_algebra_projection
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_algebra_rename
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_algebra_restriction
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_algebra_summarization
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_relation_base
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_relation_operation_binary
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_relation_operation_limit
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_relation_operation_offset
  - Axiom::SQL::Generator::Relation::Unary#visit_axiom_relation_operation_sorted
  - Axiom::SQL::Generator::Visitor#self.method_for
  - each
  max_statements: 2
UncommunicativeMethodName:
  enabled: true
  exclude:
  - Date#iso8601
  - DateTime#iso8601
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Axiom::SQL::Generator::Function::Predicate#new_from_enumerable_predicate
  - Axiom::SQL::Generator::Function::Predicate#optional?
  - Axiom::SQL::Generator::Identifier#visit_identifier
  - Axiom::SQL::Generator::Literal#visit_numeric
  - Axiom::SQL::Generator::Literal#visit_string
  max_helper_calls: 0
